INSERT INTO status VALUES (1, 'Queued') ON CONFLICT DO NOTHING;
INSERT INTO status VALUES (2, 'Sent') ON CONFLICT DO NOTHING;
INSERT INTO status VALUES (3, 'Failed') ON CONFLICT DO NOTHING;
INSERT INTO status VALUES (4, 'Rejected') ON CONFLICT DO NOTHING;
